const SampleData = [
  {
    name: "Classic White T-Shirt",
    price: 15.99,
    brand: "H&M",
    category: "Tops",
  },
  {
    name: "Skinny Jeans",
    price: 39.99,
    brand: "Zara",
    category: "Bottoms",
  },
  {
    name: "Striped Cotton Dress",
    price: 29.99,
    brand: "Forever 21",
    category: "Dresses",
  },
  {
    name: "Knit Sweater",
    price: 45.5,
    brand: "Gap",
    category: "Sweaters",
  },
  {
    name: "Leather Jacket",
    price: 99.99,
    brand: "Mango",
    category: "Outerwear",
  },
  {
    name: "Plaid Flannel Shirt",
    price: 25.0,
    brand: "Abercrombie & Fitch",
    category: "Shirts",
  },
  {
    name: "Denim Shorts",
    price: 19.99,
    brand: "American Eagle",
    category: "Shorts",
  },
  {
    name: "Maxi Skirt",
    price: 34.99,
    brand: "ASOS",
    category: "Skirts",
  },
  {
    name: "Polo Shirt",
    price: 29.99,
    brand: "Ralph Lauren",
    category: "Tops",
  },
  {
    name: "V-Neck Sweater",
    price: 55.0,
    brand: "Banana Republic",
    category: "Sweaters",
  },
  {
    name: "Printed Leggings",
    price: 20.5,
    brand: "Nike",
    category: "Bottoms",
  },
  {
    name: "Hooded Sweatshirt",
    price: 39.99,
    brand: "Adidas",
    category: "Sweatshirts",
  },
  {
    name: "Chino Pants",
    price: 49.99,
    brand: "Dockers",
    category: "Pants",
  },
  {
    name: "Cropped Blouse",
    price: 27.99,
    brand: "Topshop",
    category: "Tops",
  },
  {
    name: "Tailored Suit",
    price: 199.99,
    brand: "Hugo Boss",
    category: "Suits",
  },
  {
    name: "Trench Coat",
    price: 89.99,
    brand: "Burberry",
    category: "Outerwear",
  },
  {
    name: "Sweatpants",
    price: 24.5,
    brand: "Champion",
    category: "Bottoms",
  },
  {
    name: "Crop Top",
    price: 14.99,
    brand: "Missguided",
    category: "Tops",
  },
  {
    name: "Athletic Shorts",
    price: 22.99,
    brand: "Under Armour",
    category: "Shorts",
  },
  {
    name: "Silk Blouse",
    price: 59.99,
    brand: "Equipment",
    category: "Tops",
  },
  {
    name: "Cashmere Cardigan",
    price: 129.99,
    brand: "J.Crew",
    category: "Sweaters",
  },
  {
    name: "Cargo Pants",
    price: 37.5,
    brand: "Levi's",
    category: "Pants",
  },
  {
    name: "Midi Dress",
    price: 49.99,
    brand: "Mango",
    category: "Dresses",
  },
  {
    name: "Biker Jacket",
    price: 79.99,
    brand: "AllSaints",
    category: "Outerwear",
  },
  {
    name: "Tie-Dye T-Shirt",
    price: 18.0,
    brand: "Urban Outfitters",
    category: "Tops",
  },
  {
    name: "Corduroy Pants",
    price: 34.99,
    brand: "Gap",
    category: "Pants",
  },
  {
    name: "Wrap Skirt",
    price: 27.5,
    brand: "H&M",
    category: "Skirts",
  },
  {
    name: "Printed Blouse",
    price: 22.99,
    brand: "Zara",
    category: "Tops",
  },
  {
    name: "Distressed Jeans",
    price: 44.99,
    brand: "American Eagle",
    category: "Bottoms",
  },
  {
    name: "Ruffle Sleeve Top",
    price: 33.5,
    brand: "Forever 21",
    category: "Tops",
  },
  {
    name: "Tweed Jacket",
    price: 89.99,
    brand: "Chanel",
    category: "Outerwear",
  },
  {
    name: "Pleated Midi Skirt",
    price: 39.99,
    brand: "Zara",
    category: "Skirts",
  },
  {
    name: "Button-Up Shirt",
    price: 28.0,
    brand: "J.Crew",
    category: "Shirts",
  },
  {
    name: "Cargo Shorts",
    price: 29.99,
    brand: "Gap",
    category: "Shorts",
  },
  {
    name: "Cashmere Sweater",
    price: 149.99,
    brand: "Nordstrom",
    category: "Sweaters",
  },
  {
    name: "Denim Jacket",
    price: 59.99,
    brand: "Levi's",
    category: "Outerwear",
  },
  {
    name: "High-Waisted Leggings",
    price: 28.5,
    brand: "Lululemon",
    category: "Bottoms",
  },
  {
    name: "Floral Print Dress",
    price: 55.0,
    brand: "Kate Spade",
    category: "Dresses",
  },
  {
    name: "Puffer Vest",
    price: 49.99,
    brand: "Patagonia",
    category: "Outerwear",
  },
  {
    name: "Graphic Tee",
    price: 19.99,
    brand: "Threadless",
    category: "Tops",
  },
  {
    name: "Wide-Leg Pants",
    price: 42.5,
    brand: "ASOS",
    category: "Pants",
  },
  {
    name: "Bodycon Dress",
    price: 34.99,
    brand: "Boohoo",
    category: "Dresses",
  },
  {
    name: "V-Neck Blouse",
    price: 24.99,
    brand: "Express",
    category: "Tops",
  },
  {
    name: "Quilted Jacket",
    price: 79.99,
    brand: "Barbour",
    category: "Outerwear",
  },
  {
    name: "Cargo Skirt",
    price: 32.5,
    brand: "Free People",
    category: "Skirts",
  },
  {
    name: "Cropped Hoodie",
    price: 29.99,
    brand: "Nike",
    category: "Sweatshirts",
  },
  {
    name: "Leather Pants",
    price: 129.99,
    brand: "Rag & Bone",
    category: "Bottoms",
  },
  {
    name: "Peplum Top",
    price: 26.99,
    brand: "Charlotte Russe",
    category: "Tops",
  },
  {
    name: "Ripped Skinny Jeans",
    price: 49.99,
    brand: "Hollister",
    category: "Bottoms",
  },
  {
    name: "Maxi Cardigan",
    price: 37.5,
    brand: "Old Navy",
    category: "Sweaters",
  },
];

export default SampleData;
